name: Build Kernel

on:
  push:
    branches:
      - 14-kinesis-v10
  pull_request:
    branches:
      - 14-kinesis-v10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk repo python

    - name: Clone GCC
      run: |
        git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 --depth=1

    - name: Clone Clang
      run: |
        git clone -b clang-r498229b https://github.com/Xiaomi-SD720G-Devices/AOSP-clang.git prebuilts/clang/host/linux-x86/clang-r498229b --depth=1

    - name: Set up build environment
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH="$PWD/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:$PWD/prebuilts/clang/host/linux-x86/clang-r498229b/bin:$PATH"
        export KBUILD_COMPILER_STRING="clang version $(clang --version | head -n 1 | cut -d ' ' -f 4)"

    - name: Build Kernel
      run: |
        make O=out ARCH=arm64 vendor/miatoll.defconfig
        make -j$(nproc --all) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi-

    - name: Create flashable zip
      run: |
        mkdir -p anykernel
        git clone https://github.com/osm0sis/AnyKernel3.git anykernel
        cp out/arch/arm64/boot/Image.gz-dtb anykernel/
        cd anykernel
        zip -r9 kernel-flashable.zip * -x .git README.md *placeholder

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: kernel-flashable
        path: anykernel/kernel-flashable.zip
